# -*- coding: utf-8 -*-
"""t_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozp5SBf3ZekKc3J3Pm1tdFsKXaqR40V7

# Introdução

Esse documento possibilita o cálculo de um teste de hipóteses usando t-test. 

### Instruções de uso:

Para utilizá-lo, basta colocar o caminho do arquivo csv na variável "name_csv", o nome da coluna de data na variável "column_date", a data de início da base de entrada na variável "init_date" e a data antes da campanha a ser analisada na variável "end_date".

Feito isso, basta rodar as células abaixo e ele dirá se a hipótese nula deve ser aceita ou rejeitada.
"""

# Path do arquivo csv de entrada:
name_csv = ""

# Nome da coluna de data:
column_date = ""

# Primeira data da base:
init_date = "2020-01-01" #Apenas um exemplo

# Data do evento a ser analisado (a campanha, por exemplo).
end_date = "2020-04-22" #Apenas um exemplo

# P-valor aceitável

p_value = 0.05

from scipy.stats import ttest_ind
import numpy as np

# Lendo o arquivo csv
df = pd.read_csv(name_csv)

# Transformando a coluna de data em datetime
df[column_date] = pd.to_datetime(df[column_date], infer_datetime_format=True)

# Setando a coluna de data como indice
df.set_index(column_date, inplace=True)

df1 = df.loc[init_date:end_date,:]

df2 = df.loc[end_date:,:]

print(df1)
print(df2)
df1_mean = np.mean(df1)
df2_mean = np.mean(df2)
print("df1 mean value:",df1_mean)
print("df2 mean value:",df2_mean)
df1_std = np.std(df1)
df2_std = np.std(df2)
print("df1 std value:",df1_std)
print("df2 std value:",df2_std)
ttest,pval = ttest_ind(df1,df2)
print("p-value",pval)
if pval < p_value:
  print("Rejeita a hipótese nula (houve variação significativa)")
else:
  print("Aceita a hipótese nula (não houve variação significativa)")